const PLATFORMS = [
  { platform: 'facebook', name: 'Facebook', color: '#1877F2', oauthSupported: true },
  { platform: 'instagram', name: 'Instagram', color: '#E4405F', oauthSupported: true },
  { platform: 'threads', name: 'Threads', color: '#000000', oauthSupported: true },
  { platform: 'twitter', name: 'Twitter / X', color: '#1DA1F2', oauthSupported: true },
  { platform: 'linkedin', name: 'LinkedIn', color: '#0A66C2', oauthSupported: true },
  { platform: 'youtube', name: 'YouTube', color: '#FF0000', oauthSupported: true },
  { platform: 'pinterest', name: 'Pinterest', color: '#E60023', oauthSupported: true },
  { platform: 'snapchat', name: 'Snapchat', color: '#FFFC00', oauthSupported: false },
  { platform: 'reddit', name: 'Reddit', color: '#FF4500', oauthSupported: true },
  { platform: 'tumblr', name: 'Tumblr', color: '#36465D', oauthSupported: true },
  { platform: 'telegram', name: 'Telegram', color: '#0088CC', oauthSupported: false },
  { platform: 'whatsapp_business', name: 'WhatsApp Business', color: '#25D366', oauthSupported: false },
  { platform: 'discord', name: 'Discord', color: '#5865F2', oauthSupported: true },
  { platform: 'twitch', name: 'Twitch', color: '#9146FF', oauthSupported: true },
  { platform: 'medium', name: 'Medium', color: '#000000', oauthSupported: true },
  { platform: 'quora', name: 'Quora', color: '#B92B27', oauthSupported: false },
  { platform: 'vk', name: 'VK', color: '#4C75A3', oauthSupported: true },
  { platform: 'weibo', name: 'Weibo', color: '#E6162D', oauthSupported: false },
  { platform: 'mastodon', name: 'Mastodon', color: '#6364FF', oauthSupported: true },
  { platform: 'bluesky', name: 'Bluesky', color: '#0085FF', oauthSupported: false },
  { platform: 'behance', name: 'Behance', color: '#1769FF', oauthSupported: true },
  { platform: 'dribbble', name: 'Dribbble', color: '#EA4C89', oauthSupported: true },
  { platform: 'github', name: 'GitHub', color: '#181717', oauthSupported: true },
  { platform: 'producthunt', name: 'Product Hunt', color: '#DA552F', oauthSupported: true },
];

module.exports = PLATFORMS;
